name: "PR Description Check"
description: "an action that will check if the PR description contains the required sections"

inputs:
  gh-token:
    description: Github token
    required: true
runs:
  using: "node20"
  main: "./dist/index.js"
