name: "PR Description Check"
description: "an action that will check if the PR description contains the required sections"

inputs:
  gh-token:
    description: Github token
    required: true

  required-sections:
    description: "List of required sections in the PR description"
    required: false
    default: "description,how to test it,approach"

runs:
  using: "node20"
  main: "./dist/index.js"

branding:
  icon: "bookmark"
  color: "purple"
