name: "PR description check"
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main, develop, master]

jobs:
  check-description:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "Check PR Description"
        uses: "./"
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          required-sections: "description,how to test it,approach"
